name: Whitesource Unified Agent Scan - GO

on:
  push:
    branches: [release* ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        export GOPATH=/home/runner/work
        echo "GOPATH IS" $GOPATH
        echo "GOROOT IS " $GOROOT
        echo "PATH IS" $PATH
        echo "go env GOPATH"
        go env GOPATH
        echo "apt installs"
        sudo apt update
        sudo apt install -y go-dep
        echo "godep installed"
        dep init
      
